parameters:
  vmImage: 'Ubuntu 16.04'

jobs:
- job: Build
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: |
    set -x
    echo aaaaaaaaaaaaaaaaaaa
    echo aaaaaaaaaaaaaaaaaaa
    echo aaaaaaaaaaaaaaaaaaa
    echo aaaaaaaaaaaaaaaaaaa
    echo aaaaaaaaaaaaaaaaaaa
